### ISSUE TITLE
Referencing the preprint as in chemrxiv.org

### ISSUE THREAD

**Issue by rgiessmann** [EnzymeML/enzymeml.github.io#1]
Hi @JR-1991 and co,

I tried to fork this repo and propose a pull request myself, but actually didn't manage to understand the structure on where to change stuff. 🙈 

I would just like to propose to reference your preprint as 

https://doi.org/10.33774/chemrxiv-2021-bkxzw

instead of offering it as a download. So we can already cite it with a DOI. 😊 

What do you think? Best,
   Robert

**Comment by fbergmann** [comment]
that would be the place to change it. Let me know if that is what you had in mind or wanted to have a different formulation.

**Comment by rgiessmann** [comment]
Hi Frank @fbergmann , sorry for not replying -- everything just perfect! I will close this now. Thanks!
